# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files

-   repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
    -   id: black

-   repo: https://github.com/hadialqattan/pycln
    rev: v2.2.0
    hooks:
    -   id: pycln
        exclude: ^.__init__.py$
        args: [--skip-imports=schedule]

-   repo: https://github.com/PyCQA/pylint
    rev: v3.0.0a6
    hooks:
    -   id: pylint
        files: "\\.(py)$"
        args: [--fail-under=7, -d E0401, "--ignore-paths=interfaces/API/*"]

-   repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
    -   id: isort
        name: isort (python)

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.4.1
    hooks:
    -   id: mypy
        args: [--strict]
